#This will check the lint error and run all the tests 

name: test

on: 
  push: 
    branches: [ "*" ]
  pull_request: 
    branches: [ "*" ]

jobs:
  #Running unit tests to make sure everything is fine
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x', '22.x', '23.x']

    steps:
      #Checking if the code in repo if it is feasible
      - name: Checkout code
        uses: actions/checkout@v4

      #Setting node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' #selecting package manager

      #Installing all the packages and dependencises to run the app
      - name: Installing dependencies
        run: npm ci

      #testing
      - name: Run test
        run: npm test

      #Checking security and Vulnerabilities
      - name: Audit 
        run: npm audit


    

      